In [1]:
import pandas as pd

In [2]:
import numpy as np

In [4]:
dfmovie = pd.read_csv("D:\DATASETS\DATASETS\Outlier Detection Dataset\Onehotencoding dataset\movie_review.csv")

In [5]:
dfmovie

,age,gender,education,review
0,30,Female,School,Average
1,68,Female,UG,Poor
2,70,Female,PG,Good
3,72,Female,PG,Good
4,16,Female,UG,Average
5,31,Female,School,Average
6,18,Male,School,Good
7,60,Female,School,Poor
8,65,Female,UG,Average
9,74,Male,UG,Good


In [6]:
dfmovie.head()

,age,gender,education,review
0,30,Female,School,Average
1,68,Female,UG,Poor
2,70,Female,PG,Good
3,72,Female,PG,Good
4,16,Female,UG,Average


In [7]:
dfmovie.dtypes

age           int64
gender       object
education    object
review       object
dtype: object

In [8]:
dfmovie["gender"]

0     Female
1     Female
2     Female
3     Female
4     Female
5     Female
6       Male
7     Female
8     Female
9       Male
10    Female
11      Male
12      Male
13    Female
14      Male
15      Male
16      Male
17    Female
18      Male
19      Male
20    Female
21      Male
22    Female
23    Female
24    Female
25    Female
26    Female
27    Female
28      Male
29    Female
30      Male
31    Female
32      Male
33    Female
34      Male
35      Male
36    Female
37      Male
38    Female
39      Male
40      Male
41      Male
42    Female
43      Male
44    Female
45      Male
46    Female
47    Female
48    Female
49    Female
Name: gender, dtype: object

In [9]:
dfmovie["gender"].unique()

array(['Female', 'Male'], dtype=object)

In [10]:
dfmovie["education"]

0     School
1         UG
2         PG
3         PG
4         UG
5     School
6     School
7     School
8         UG
9         UG
10        UG
11        UG
12    School
13    School
14        PG
15        UG
16        UG
17        UG
18    School
19        PG
20    School
21        PG
22        PG
23    School
24        PG
25    School
26        PG
27        PG
28    School
29        UG
30        UG
31    School
32        UG
33        PG
34    School
35    School
36        UG
37        PG
38    School
39        PG
40    School
41        PG
42        PG
43        PG
44        UG
45        PG
46        PG
47        PG
48        UG
49        UG
Name: education, dtype: object

In [11]:
dfmovie["education"].unique()

array(['School', 'UG', 'PG'], dtype=object)

In [12]:
dfmovie.head()

,age,gender,education,review
0,30,Female,School,Average
1,68,Female,UG,Poor
2,70,Female,PG,Good
3,72,Female,PG,Good
4,16,Female,UG,Average


In [13]:
dfmovie["review"]

0     Average
1        Poor
2        Good
3        Good
4     Average
5     Average
6        Good
7        Poor
8     Average
9        Good
10       Good
11       Good
12       Poor
13    Average
14       Poor
15       Poor
16       Poor
17       Poor
18       Good
19       Poor
20    Average
21    Average
22       Poor
23       Good
24    Average
25       Good
26       Poor
27       Poor
28       Poor
29    Average
30    Average
31       Poor
32    Average
33       Good
34    Average
35       Poor
36       Good
37    Average
38       Good
39       Poor
40       Good
41       Good
42       Good
43       Poor
44    Average
45       Poor
46       Poor
47       Good
48       Good
49       Good
Name: review, dtype: object

In [14]:
dfmovie["review"].unique()

array(['Average', 'Poor', 'Good'], dtype=object)

### Ordinal Encoder

In [15]:
from sklearn.preprocessing import OrdinalEncoder

In [16]:
ord = OrdinalEncoder()

In [17]:
ord

OrdinalEncoder()

In [18]:
ord.fit(dfmovie[["education"]])

OrdinalEncoder()

In [19]:
ord.transform(dfmovie[["education"]])

array([[1.],
       [2.],
       [0.],
       [0.],
       [2.],
       [1.],
       [1.],
       [1.],
       [2.],
       [2.],
       [2.],
       [2.],
       [1.],
       [1.],
       [0.],
       [2.],
       [2.],
       [2.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [2.],
       [2.],
       [1.],
       [2.],
       [0.],
       [1.],
       [1.],
       [2.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [2.],
       [0.],
       [0.],
       [0.],
       [2.],
       [2.]])

In [21]:
ary_edu = ord.transform(dfmovie[["education"]])

In [22]:
ary_edu

array([[1.],
       [2.],
       [0.],
       [0.],
       [2.],
       [1.],
       [1.],
       [1.],
       [2.],
       [2.],
       [2.],
       [2.],
       [1.],
       [1.],
       [0.],
       [2.],
       [2.],
       [2.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [2.],
       [2.],
       [1.],
       [2.],
       [0.],
       [1.],
       [1.],
       [2.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [2.],
       [0.],
       [0.],
       [0.],
       [2.],
       [2.]])

In [25]:
ord.categories_

[array(['PG', 'School', 'UG'], dtype=object)]

In [24]:
dfmovie.head()

,age,gender,education,review
0,30,Female,School,Average
1,68,Female,UG,Poor
2,70,Female,PG,Good
3,72,Female,PG,Good
4,16,Female,UG,Average


In [27]:
dfmovie["education"] = ary_edu

In [28]:
dfmovie

,age,gender,education,review
0,30,Female,1.0,Average
1,68,Female,2.0,Poor
2,70,Female,0.0,Good
3,72,Female,0.0,Good
4,16,Female,2.0,Average
5,31,Female,1.0,Average
6,18,Male,1.0,Good
7,60,Female,1.0,Poor
8,65,Female,2.0,Average
9,74,Male,2.0,Good


### Label Encoder

In [29]:
from sklearn.preprocessing import LabelEncoder

In [30]:
label = LabelEncoder()

In [31]:
label

LabelEncoder()

In [32]:
label.fit(dfmovie["review"])

LabelEncoder()

In [33]:
label.transform(dfmovie["review"])

array([0, 2, 1, 1, 0, 0, 1, 2, 0, 1, 1, 1, 2, 0, 2, 2, 2, 2, 1, 2, 0, 0,
       2, 1, 0, 1, 2, 2, 2, 0, 0, 2, 0, 1, 0, 2, 1, 0, 1, 2, 1, 1, 1, 2,
       0, 2, 2, 1, 1, 1])

In [34]:
ary_rev = label.transform(dfmovie["review"])

In [35]:
ary_rev

array([0, 2, 1, 1, 0, 0, 1, 2, 0, 1, 1, 1, 2, 0, 2, 2, 2, 2, 1, 2, 0, 0,
       2, 1, 0, 1, 2, 2, 2, 0, 0, 2, 0, 1, 0, 2, 1, 0, 1, 2, 1, 1, 1, 2,
       0, 2, 2, 1, 1, 1])

In [36]:
label.classes_

array(['Average', 'Good', 'Poor'], dtype=object)

In [37]:
dfmovie.head()

,age,gender,education,review
0,30,Female,1.0,Average
1,68,Female,2.0,Poor
2,70,Female,0.0,Good
3,72,Female,0.0,Good
4,16,Female,2.0,Average


In [38]:
dfmovie["review"] = ary_rev

In [ ]:
dfmovie